In [3]:
import pandas as pd 
import numpy as np

path = 'cases.csv'
df = pd.read_csv(path)
df

,caseid,subjectid,casestart,caseend,anestart,aneend,opstart,opend,adm,dis,...,intraop_colloid,intraop_ppf,intraop_mdz,intraop_ftn,intraop_rocu,intraop_vecu,intraop_eph,intraop_phe,intraop_epi,intraop_ca
0,1,5955,0,11542,-552,10848.0,1668,10368,-236220,627780,...,0,120,0.0,100,70,0,10,0,0,0
1,2,2487,0,15741,-1039,14921.0,1721,14621,-221160,1506840,...,0,150,0.0,0,100,0,20,0,0,0
2,3,2861,0,4394,-590,4210.0,1090,3010,-218640,40560,...,0,0,0.0,0,50,0,0,0,0,0
3,4,1903,0,20990,-778,20222.0,2522,17822,-201120,576480,...,0,80,0.0,100,100,0,50,0,0,0
4,5,4416,0,21531,-1009,22391.0,2591,20291,-67560,3734040,...,0,0,0.0,0,160,0,10,900,0,2100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6383,6384,5583,0,15248,-260,15640.0,2140,14140,-215340,648660,...,0,150,0.0,0,90,0,20,0,0,0
6384,6385,2278,0,20643,-544,20996.0,2396,19496,-225600,1675200,...,0,100,0.0,0,100,0,25,30,0,300
6385,6386,4045,0,19451,-667,19133.0,3533,18233,-200460,836340,...,0,70,0.0,0,130,0,10,0,0,0
6386,6387,5230,0,12025,-550,12830.0,1730,11030,-227760,377040,...,0,120,0.0,0,50,0,0,0,0,0
6387,6388,1306,0,10249,-79,10121.0,2321,9221,-312060,379140,...,500,120,0.0,0,90,0,20,0,0,0

In [11]:
numeric_features = ['age', 'height', 'weight', 'preop_hb', 'preop_plt']
categorical_features = ['sex', 'optype', 'position', 'approach', 'ane_type', 'emop']
target_variable = 'death_inhosp'

# Split features and target
X = df[numeric_features + categorical_features + [target_variable]]
X['emop'] = X['emop'].replace({0: 'No', 1: 'Yes'})
X

C:\Users\jayde\AppData\Local\Temp\ipykernel_39704\1983087377.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['emop'] = X['emop'].replace({0: 'No', 1: 'Yes'})

,age,height,weight,preop_hb,preop_plt,sex,optype,position,approach,ane_type,emop,death_inhosp
0,77.0,160.2,67.50,14.1,189.0,M,Colorectal,Lithotomy,Open,General,No,0
1,54.0,167.3,54.80,10.2,251.0,M,Stomach,Supine,Open,General,No,0
2,62.0,169.1,69.70,14.2,373.0,M,Biliary/Pancreas,Reverse Trendelenburg,Videoscopic,General,No,0
3,74.0,160.6,53.00,14.4,275.0,M,Stomach,Reverse Trendelenburg,Videoscopic,General,No,0
4,66.0,171.0,59.70,10.1,67.0,M,Vascular,Prone,Open,General,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...
6383,64.0,161.5,63.00,14.5,279.0,M,Stomach,Supine,Open,General,No,0
6384,69.0,159.3,62.30,15.2,239.0,M,Colorectal,Lithotomy,Videoscopic,General,No,0
6385,61.0,151.7,43.25,12.6,276.0,F,Stomach,Supine,Videoscopic,General,No,0
6386,24.0,155.7,55.50,12.5,214.0,F,Biliary/Pancreas,Supine,Robotic,General,No,0
6387,47.0,150.0,51.50,8.6,549.0,F,Major resection,Lithotomy,Open,General,No,0

In [12]:
unique_values = {col: X[col].unique() for col in X[categorical_features].columns}

In [13]:
unique_values

{'sex': array(['M', 'F'], dtype=object),
 'optype': array(['Colorectal', 'Stomach', 'Biliary/Pancreas', 'Vascular',
        'Major resection', 'Breast', 'Minor resection', 'Transplantation',
        'Hepatic', 'Thyroid', 'Others'], dtype=object),
 'position': array(['Lithotomy', 'Supine', 'Reverse Trendelenburg', 'Prone',
        'Left lateral decubitus', 'Right lateral decubitus', nan,
        'Trendelenburg', 'Sitting', 'Left kidney', 'Right kidney'],
       dtype=object),
 'approach': array(['Open', 'Videoscopic', 'Robotic'], dtype=object),
 'ane_type': array(['General', 'Spinal', 'Sedationalgesia'], dtype=object),
 'emop': array(['No', 'Yes'], dtype=object)}

In [14]:
X.to_csv("chart_data.csv", index=False)